# Ensure we're using the most up-to-date version of Ruby.
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
  - 'app/frost/pins/manual_archiver.rb'
  - 'app/frost/pins/auto_archiver.rb'
  - 'app/frost/models/commands.rb'
  - 'app/frost/models/embeds.rb'

# Double quotes are preferable for me.
Style/StringLiterals:
  EnforcedStyle: double_quotes
  
# Most of these metrics are useless.
Metrics/PerceivedComplexity:
  Enabled: false

# Most of these metrics are useless.
Metrics/CyclomaticComplexity:
  Enabled: false

# Most of these metrics are useless.
Metrics/ParameterLists:
  Enabled: false

# Most of these metrics are useless.
Metrics/MethodLength:
  Enabled: false

# Most of these metrics are useless.
Metrics/ClassLength:
  Enabled: false

# I don't really use modules normally.
Style/Documentation:
  Enabled: false

# Most of these metrics are useless.
Metrics/BlockLength:
  Enabled: false

# Most of these metrics are useless.
Metrics/AbcSize:
  Enabled: false

# Appropriate safeguards have been taken.
Security/Eval:
  Enabled: false

# The usage of class variables is intentional.
Style/ClassVars:
  Enabled: false

# I don't like the extra end it introduces.
Style/IfUnlessModifier:
  Enabled: false

# I prefer to keep the block for consistency.
Lint/UnusedBlockArgument:
  Enabled: false

# Many of our interaction responses are lengthy.
Layout/LineLength:
  Enabled: false

# I prefer positional arguments.
Style/OptionalBooleanParameter:
  Enabled: false