# Ensure we're using the most up-to-date version of Ruby.
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

# Double quotes are preferable for me.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Most of these metrics are useless.
Metrics:
  Enabled: false

# I don't really use modules normally.
Style/Documentation:
  Enabled: false

# The usage of class variables is intentional.
Style/ClassVars:
  Enabled: false

# I don't like the extra end it introduces.
Style/IfUnlessModifier:
  Enabled: false

# Many of our interaction responses are lengthy.
Layout/LineLength:
  Enabled: false

# This is fine. Sometimes I just want to swallow errors.
Style/RescueModifier:
  Enabled: false

# I generally think this python-like idiom is okay to use.
Style/ParallelAssignment:
  Enabled: false

# This seems to sometimes trigger falsely with a block so.
Style/EmptyLiteral:
  Enabled: false

# This seems to sometimes trigger falsely with one-line rescues.
Style/RedundantParentheses:
  Enabled: false