# Ensure we're using the most up-to-date version of Ruby.
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
  - 'src/frost/commands/commands.rb'
  - 'src/frost/data/lavalink.rb'
  - 'src/frost/data/embeds.rb'

# Most of these metrics are useless.
Metrics/PerceivedComplexity:
  Enabled: false

# Most of these metrics are useless.
Metrics/CyclomaticComplexity:
  Enabled: false

# Most of these metrics are useless.
Metrics/MethodLength:
  Enabled: false

# I don't really use modules normally.
Style/Documentation:
  Enabled: false

# Most of these metrics are useless.
Metrics/BlockLength:
  Enabled: false

# Most of these metrics are useless.
Metrics/AbcSize:
  Enabled: false

# The usage of class variables is intentional.
Style/ClassVars:
  Enabled: false

# Appropriate safeguards have been taken.
Security/Eval:
  Enabled: false
