networks:
  main:
    name: main

services:
  lavalink:
    image: 'ghcr.io/lavalink-devs/lavalink:4'
    container_name: lavalink
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "Lavalink has started."]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=DroidDevelopment
    volumes:
      - './application.yml:/opt/Lavalink/application.yml'
      - './plugins/:/opt/Lavalink/plugins/'
    networks:
      - main
    expose:
      - 2333

  app:
    build: .
    container_name: frost
    restart: unless-stopped
    networks:
      - main
    depends_on:
      - lavalink