networks:
  main:
    name: main

services:
  lavalink:
    image: 'ghcr.io/lavalink-devs/lavalink:4-alpine'
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=YOUR_PASSWORD_HERE
    volumes:
      - './application.yml:/opt/Lavalink/application.yml'
      - './plugins/:/opt/Lavalink/plugins/'
    networks:
      - main
    expose:
      - 2333

  app:
    build: .
    container_name: frost
    restart: unless-stopped
    networks:
      - main
    depends_on:
      - lavalink