[Discord]
OWNER = "YOUR_ID_HERE"
TOKEN = "Bot TOKEN_HERE"
COMMANDS = []
CONTRIBUTORS = []

[Postgres]
USERNAME = ""
PASSWORD = ""
URL = ""

[Chapter]
CHANNEL = ""
LINK = ""

[Music]
YOUTUBE = ""
CLIENT_ID = ""
CLIENT_SECRET = ""