[Discord]
OWNER = "YOUR_ID_HERE"
TOKEN = "Bot TOKEN_HERE"
CONTRIBUTORS = []

[Postgres]
USERNAME = ""
PASSWORD = ""
URL = ""

[Chapter]
CHANNEL = ""
LINK = ""

[Music]
YOUTUBE = ""
SPOTIFY_CLIENT = ""
SPOTIFY_SECRET = ""