# frozen_string_literal: true

module AffectionCommands
  extend Discordrb::EventContainer

  # Noms another user.
  def nom_member: (untyped data) -> untyped
  
  # Hugs another user.
  def hug_member: (untyped data) -> untyped
  
  # Bonks another user.
  def bonk_member: (untyped data) -> untyped

  # Pokes another user.
  def poke_member: (untyped data) -> untyped
  
  # Shows your anger.
  def angry_member: (untyped data) -> untyped

  # Punches another user.
  def punch_member: (untyped data) -> untyped
                  
  # Tells a member to sleep.
  def sleep_member: (untyped data) -> untyped
end
