# frozen_string_literal: true

module SnowballFights
  extend Discordrb::EventContainer

  # Collects and adds a snowball to the DB.
  def collect_snowball: (untyped data) -> untyped

  # Allows contributors to steal snowballs from others.
  def steal_snowball: (untyped data) -> (nil | untyped)

  # Throws a snowball at someone and removes one from the DB.
  def throw_snowball: (untyped data) -> (nil | untyped)
end
