# frozen_string_literal: true

# A response message to an interaction.
RESPONSE = {
  1 => "Your role has been created! You can always edit your role using the </booster role edit:1330463676414693407> command.",
  2 => "Your role has been successfully edited!",
  3 => "Your role has been successfully deleted! Feel free to make a new role at any time.",
  4 => "You've already claimed your custom role on this server.",
  5 => "This functionality has not been enabled on this server.",
  6 => "You have been banned from using this feature.",
  7 => "Invalid name parameter.",
  8 => "You aren't boosting this server.",
  9 => "We couldn't find your role. Please use the </booster role claim:1330463676414693407> command to claim your role.",
  10 => "Made by *droid00000* using the [discordrb library!](<https://github.com/shardlab/discordrb>)",
  11 => "Invalid status parameter.",
  12 => "You must be a contributor to use this command.",
  13 => "Successfully updated the status! Thank you for contributing to my bot!",
  14 => "You're out of snowballs! You can collect more using the </collect snowball:1325631057734926339> command!",
  15 => "You missed!",
  16 => "This user doesn't have any snowballs.",
  17 => "That role cannot be updated.",
  18 => "``401: Unauthorized``",
  19 => "The bot has powered off.",
  20 => "Succesfully archived one pinned message!",
  21 => "This user doesn't have enough snowballs.",
  22 => "Successfully set the archive channel to: <#%s>",
  23 => "You've already setup event perks for this role.",
  24 => "Successfully setup event perks for this role: <@&%s>",
  25 => "This user is already a booster in this server.",
  26 => "Successfully added the following user to the database: <@%s>",
  27 => "This user isn't boosting your server, or hasn't claimed their role.",
  28 => "Successfully removed the following user from the database: <@%s>",
  29 => "This user has already been banned from using the booster perks functionality.",
  30 => "Successfully banned the following user from using the booster perks functionality: <@%s>",
  31 => "This user isn't banned from using the booster perks functionality.",
  32 => "Successfully un-banned the following user from using the booster perks functionality: <@%s>",
  33 => "Successfully set your hoist-role to the following role: <@&%s>",
  34 => "Booster perks are already disabled in this server.",
  35 => "Successfully disabled booster perks in this server.",
  36 => "This server hasn't enabled the pin archiver.",
  37 => "Successfully disabled the pin archiver in this server.",
  38 => "This server hasn't enabled event perks.",
  39 => "Successfully disabled event perks in this server.",
  40 => "Locked down **%s** %s.",
  41 => "Successfully unlocked the server.",
  42 => "This message doesn't have any emojis.",
  43 => "Added this emoji to the server:",
  44 => "Added **%s** emoji(s) to the server.",
  45 => "This server is out of emoji slots.",
  46 => "This server has reached the maximum amount of roles.",
  47 => "The bot needs to have the ``manage roles`` permission to do this.",
  48 => "The bot needs to have the ``manage expressions`` permission to do this.",
  49 => "The bot needs to have the ``manage channels`` permission to do this.",
  50 => "Successfully restarting the bot.",
  51 => "You need to have the ``administrator`` permission to do this.",
  52 => "The bot needs to have the ``manage server`` permission to do this.",
  53 => "Successfully banned **%s** user(s).",
  54 => "You do not have permission to ban any user you've specified.",
  55 => "There are many reasons as to why the chapter could be delayed. Please be paitent and wait.",
  56 => "**Next Chapter:** <t:%s:D>",
  57 => "Successfully blocked <@%s> from viewing this channel.",
  58 => "You cannot perform this action on this member.",
  59 => "The bot needs to have the ``timeout members`` permission to do this.",
  60 => "Invalid duration parameter.",
  61 => "A mute can only last up to 28 days.",
  62 => "You may not mute this user.",
  63 => "Successfully timed out <@%s>.",
  64 => "There aren't any emojis stats available for this server!",
  65 => "Changed this member's nickname: <@%s>",
  66 => "The bot needs to have the ``manage nicknames`` permission to do this.",
  67 => "The bot needs to have the ``manage messages`` permission to do this.",
  68 => "Successfully deleted **%s** message(s).",
  69 => "The bot doesn't have permissions to do this!",
  70 => "Stole **%s** snowballs!",
  85 => "Heads!",
  86 => "Tails!",
  92 => "Successfully seeked to ``%s``.",
  93 => "Disabled event perks for this role: <@&%s>",
  94 => "You aren't a head of house.",
  95 => "This isn't your house.",
  96 => "You don't have permission to use this button.",
  97 => "Drained all the emojis into the database.",
  98 => "The bot isn't playing anything!",
  99 => "The bot doesn't have permission to move to this channel.",
  100 => "Successfully moved channels.",
  101 => "This command can't be used here.",
  102 => "Your index is too large.",
  103 => "You haven't set your birthday.",
  104 => "This server hasn't enabled birthday perks.",
  105 => "I failed to process your birthday or timezone.",
  106 => "Successfully removed your birthday.",
  107 => "Successfully added your birthday!",
  108 => "Successfully setup birthday perks.",
  109 => "Successfully disabled birthday perks.",
  110 => "Successfully updated your notification settings.",
  112 => "You've already set your birthday.",
  113 => "You must provide at least one option.",
  114 => "**Happy Birthday <@%s>!** I hope you have an amazing one, thanks for spending some time with us! %s",
  115 => "You must provide a role when setting up this feature.",
  116 => "Successfully updated birthday perks for this server.",
  117 => "Successfully updated your birthday!",
  118 => "Please provide a valid duration.",
  119 => "The duration must be less than **twenty-four** hours.",
  120 => "Successfully disabled invites for this server.",
  121 => "Invites are currently enabled for this server.",
  122 => "Successfully enabled invites for this server.",
  123 => "You can only indefinitely disable invites in `community` servers.",
  124 => "You must provide a role when initally setting up booster perks.",
  125 => "This is not a valid timezone.",
  126 => "Successfully updated your icon settings.",
  127 => "There must be at least fifty pins in this channel.",
  128 => "This server hasn't enabled the pin archiver."
}.freeze

# Resolvable string color codes.
COLORS = {
  aquamarine: 8_388_564,
  beige: 16_119_260,
  black: 12,
  blue: 3_447_003,
  brown: 10_824_234,
  chocolate: 13_789_470,
  coral: 16_744_272,
  crimson: 14_423_100,
  cyan: 65_535,
  dark_blue: 2_123_412,
  dark_cyan: 35_723,
  dark_gray: 6_323_595,
  dark_green: 2_067_276,
  dark_magenta: 11_342_935,
  dark_orange: 11_027_200,
  dark_red: 10_038_562,
  deep_pink: 16_716_947,
  fuchsia: 15_418_782,
  gold: 15_844_367,
  gray: 8_421_504,
  green: 3_066_993,
  green_yellow: 11_403_055,
  hot_pink: 16_738_740,
  indigo: 4_915_330,
  ivory: 16_777_200,
  khaki: 15_787_660,
  lavender: 15_132_410,
  light_blue: 11_393_254,
  light_green: 9_498_256,
  light_pink: 16_758_465,
  light_yellow: 16_777_184,
  lime: 65_280,
  magenta: 15_277_667,
  maroon: 8_388_608,
  midnight_blue: 1_644_912,
  navy: 128,
  olive: 8_421_376,
  orange: 15_105_570,
  orange_red: 16_729_344,
  orchid: 14_315_734,
  pale_green: 10_025_880,
  pink: 15_418_783,
  powder_blue: 11_591_910,
  purple: 10_181_046,
  red: 15_158_332,
  royal_blue: 4_286_945,
  salmon: 16_416_882,
  silver: 12_632_256,
  sky_blue: 8_900_331,
  tan: 13_808_780,
  teal: 1_752_220,
  turquoise: 4_251_856,
  violet: 15_631_086,
  white: 16_777_215,
  yellow: 16_705_372,
  blurple: 5_793_266,
  original_blurple: 7_506_394
}.freeze

# The audit log reason shown whenever the bot does something.
REASON = {
  1 => "Birthday Roles",
  2 => "Booster Roles",
  3 => "Release Date",
  4 => "%s (ID: %s)"
}.freeze

# The time zone database source.
TZInfo::DataSource.set(:zoneinfo)

# The YAML configuration file used by the bot.
CONFIG = YAML.load_file("#{$LOAD_PATH.first}/config.yml", symbolize_names: true)

# The Postgres database instance used by the bot.
POSTGRES = Sequel.connect(CONFIG[:Postgres][:URL], extensions: :connection_validator)

POSTGRES.pool.connection_validation_timeout = -1

# A series of regular expressions utilized by the bot.
REGEX = {
  1 => /#?([0-9A-Fa-f]{6})\b/i,
  2 => /<(a?):([a-zA-Z0-9_]{1,32}):([0-9]{15,20})>/,
  3 => /fag|f@g|bitch|b1tch|faggot|whore|wh0re|tranny|tr@nny|nigger|nigga|faggot|nibba|n1g|n1gger|nigaboo|n1gga|n i g g e r|n i g g a|@everyone|r34|porn|hentai|sakimichan|patron only|pornhub|\.gg|xxxvideos|xvideos|retard|retarded|porno|deepfake|erection|thirst trap|erection|khyleri|dyke|anus|anal|blowjob|boner|cum|chink|chinky|paki|futanari|titjob|boobjob|scat|jizz|gangbang|chingchong|ziggaboo|mexcrement|kill yourself|kys|clit|orgasm|semen|foreskin|cock|ahegao|pedophile|pedophille|autist|pedos|gook|negro|rape|raper|rapist|slut|fellatio|cuck|\.com|\.org|\.net|pussy|penis|uterus|cnc|bdsm|cunt|kink|kinky|discord\.gg|join my server|thighs|th1ghs|smut|wanker|vulva|wank|titty|topless|tit|tits|swinger|hitler|swastika|strapon|spooge|jizz|shibari|cumshot|shemale|sex|chaturbate|scat|masochist|scissoring|schlong|shibari|sadism|raping|queef|pornography|pissing|pegging|pegged|paedophile|orgy|pedobear|ponyplay|nympho|nudes|nude|octopussy|omorashi|masturbate|milf|dilf|lolita|missionary|missionary style|m!ssionary style|m!ss!onary style|m!ss!0nary style|d0ggy style| kike|incest|nhentai|jailbait|handjob|g-spot|futanari|fisting|fingering|femdom|squirting|ecchi|ejaculation|erotic|doggiestyle|doggy style|doggystyle|deepthroat|date rape|daterape|dildo|clit|clitoris|camgirl|camslut|camwhore|butthole|anal|bitches|black cock|erotic|disboard|invite\.gg|higger|nate higgers|gooner|kys|kms/i
}.freeze
