# frozen_string_literal: true

COLLECT = ['https://media.tenor.com/oXY0XhDrZ_kAAAAi/menhera-chan.gif',
           'https://media.tenor.com/odNpnufgwkYAAAAC/anime-cute.gif', 'https://media.tenor.com/W7og11vOuFoAAAAC/elodrai-snowball.gif', 'https://media.tenor.com/8UrTfVBMVmwAAAAi/rock-up.gif'].freeze

THROW = ['https://media.tenor.com/FGCpXFkX3dIAAAAC/anime.gif',
         'https://media.tenor.com/PPWAjdhbGnwAAAAd/goblin-kids-goblin-baby.gif', 'https://media.tenor.com/yAvKjzxBGeoAAAAi/snowball-fight.gif', 'https://media.tenor.com/ZZeR0E20gfAAAAAC/ash-serena-ash.gif', 'https://media.tenor.com/pvMYzXPpVLIAAAAd/acchi-kocchi-anime.gif', 'https://media.tenor.com/kyxVTl1Ee2YAAAAd/senko-san-snowball.gif', 'https://media.tenor.com/9pbG2ld4H8UAAAAC/snow-snowing.gif', 'https://media.tenor.com/PfJisM8oiCwAAAAd/azumanga-daioh-azumanga.gif', 'https://media.tenor.com/sD2AcewwSMIAAAAC/snow-ball-take-down.gif', 'https://media.tenor.com/oQw7uToR0mgAAAAC/amaura-ice-dinosaur.gif', 'https://media.tenor.com/EAQwlGXm0_AAAAAC/takane-enomoto-enomoto-takane.gif', 'https://media.tenor.com/1m74jUqgxcUAAAAC/inazuma-eleven-ina11.gif', 'https://media.tenor.com/3WmCUSj3DlQAAAAd/laura-tropical-rouge-precure.gif', 'https://media.tenor.com/L4LB732P7JcAAAAd/the-prince-and-the-pauper-snowball-fight.gif', 'https://media.tenor.com/WU7P9UBpzMUAAAAd/kurumi-erika-laura.gif', 'https://media.giphy.com/media/W5TBt9C4VVWw2BOOjP/giphy.gif', 'https://media.tenor.com/qDEZGcFwVasAAAAC/snowball-carrot.gif', 'https://media.tenor.com/48IYu9PI9wMAAAAC/man-throw.gif', 'https://media.tenor.com/9pbG2ld4H8UAAAAC/snow-snowing.gif', 'https://i.imgur.com/ZO5AoH9.gif', 'https://media.tenor.com/A-7WMFWiG9UAAAAC/snow-face.gif', 'https://media.tenor.com/7ybvhz-LT4sAAAAC/snow-day-snowball-fight.gif', 'https://media.tenor.com/pvMYzXPpVLIAAAAd/acchi-kocchi-anime.gif', 'https://media.tenor.com/gQAWuiZnbZ4AAAAd/pokemon-anime.gif', 'https://media.tenor.com/ffjph2ZxJCMAAAAC/perris-howard-snowball.gif', 'https://media.tenor.com/FGCpXFkX3dIAAAAC/anime.gif'].freeze

MISS = ['https://media.giphy.com/media/ukSGgGljsKRXdiHb0h/giphy.gif',
        'https://media.tenor.com/nDxCGQUnuDEAAAAC/snowball-anime.gif', 'https://i.gifer.com/Ml2t.gif', 'https://i.pinimg.com/originals/b8/20/f9/b820f9cc3283edf2abdafa82057188fc.gif'].freeze
