# frozen_string_literal: true

# Resolvable string color codes.
COLORS = {
  aquamarine: "7fffd4",
  beige: "f5f5dc",
  black: "00000c",
  blue: "0000ff",
  brown: "a52a2a",
  chocolate: "d2691e",
  coral: "ff7f50",
  crimson: "dc143c",
  cyan: "00ffff",
  dark_blue: "00008b",
  dark_cyan: "008b8b",
  dark_gray: "a9a9a9",
  dark_green: "006400",
  dark_magenta: "8b008b",
  dark_orange: "ff8c00",
  dark_red: "8b0000",
  deep_pink: "ff1493",
  fuchsia: "ff00ff",
  gold: "ffd700",
  gray: "808080",
  green: "008000",
  green_yellow: "adff2f",
  hot_pink: "ff69b4",
  indigo: "4b0082",
  ivory: "fffff0",
  khaki: "f0e68c",
  lavender: "e6e6fa",
  light_blue: "add8e6",
  light_green: "90ee90",
  light_pink: "ffb6c1",
  light_yellow: "ffffe0",
  lime: "00ff00",
  magenta: "ff00ff",
  maroon: "800000",
  midnight_blue: "191970",
  navy: "000080",
  olive: "808000",
  orange: "ffa500",
  orange_red: "ff4500",
  orchid: "da70d6",
  pale_green: "98fb98",
  pink: "ffc0cb",
  powder_blue: "b0e0e6",
  purple: "800080",
  red: "ff0000",
  royal_blue: "4169e1",
  salmon: "fa8072",
  silver: "c0c0c0",
  sky_blue: "87ceeb",
  tan: "d2b48c",
  teal: "008080",
  turquoise: "40e0d0",
  violet: "ee82ee",
  white: "ffffff",
  yellow: "ffff00"
}.freeze

# Mapping of of country codes to timezones.
ZONES = {
  GMT: ["Greenwich Mean Time"],
  IBST: ["International Business Standard Time"],
  WET: ["Western European Time"],
  Z: ["Zulu Time (Coordinated Universal Time)"],
  EGST: ["Eastern Greenland Summer Time"],
  BST: ["British Summer Time", "Bangladesh Standard Time", "Bougainville Standard Time"],
  CET: ["Central European Time"],
  DFT: ["AIX specific equivalent of Central European Time"],
  IST: ["Irish Standard Time", "Indian Standard Time", "Israel Standard Time"],
  MET: ["Middle European Time Same zone as CET"],
  WAT: ["West Africa Time"],
  WEDT: ["Western European Daylight Time"],
  WEST: ["Western European Summer Time"],
  CAT: ["Central Africa Time"],
  CEDT: ["Central European Daylight Time"],
  CEST: ["Central European Summer Time"],
  EET: ["Eastern European Time"],
  HAEC: ["Heure Avancée d'Europe Centrale"],
  MEST: ["Middle European Summer Time Same zone as CEST"],
  SAST: ["South African Standard Time"],
  USZ1: ["Kaliningrad Time"],
  WAST: ["West Africa Summer Time"],
  EAT: ["East Africa Time"],
  EEDT: ["Eastern European Daylight Time"],
  EEST: ["Eastern European Summer Time"],
  FET: ["Further-eastern European Time"],
  IDT: ["Israel Daylight Time"],
  IOT: ["Indian Ocean Time"],
  MSK: ["Moscow Time"],
  SYOT: ["Showa Station Time"],
  IRST: ["Iran Standard Time"],
  AZT: ["Azerbaijan Time"],
  GET: ["Georgia Standard Time"],
  MUT: ["Mauritius Time"],
  RET: ["Réunion Time"],
  SAMT: ["Samara Time"],
  SCT: ["Seychelles Time"],
  VOLT: ["Volgograd Time"],
  AFT: ["Afghanistan Time"],
  IRDT: ["Iran Daylight Time"],
  HMT: ["Heard and McDonald Islands Time"],
  MAWT: ["Mawson Station Time"],
  MVT: ["Maldives Time"],
  ORAT: ["Oral Time"],
  PKT: ["Pakistan Standard Time"],
  TFT: ["Indian/Kerguelen"],
  TJT: ["Tajikistan Time"],
  TMT: ["Turkmenistan Time"],
  UZT: ["Uzbekistan Time"],
  YEKT: ["Yekaterinburg Time"],
  SLST: ["Sri Lanka Standard Time"],
  NPT: ["Nepal Time"],
  BIOT: ["British Indian Ocean Time"],
  BTT: ["Bhutan Time"],
  KGT: ["Kyrgyzstan time"],
  OMST: ["Omsk Time"],
  VOST: ["Vostok Station Time"],
  CCT: ["Cocos Islands Time"],
  MMT: ["Myanmar Time", "Myanmar Standard Time"],
  CXT: ["Christmas Island Time"],
  DAVT: ["Davis Time"],
  HOVT: ["Khovd Time"],
  ICT: ["Indochina Time"],
  KRAT: ["Krasnoyarsk Time"],
  THA: ["Thailand Standard Time"],
  WIT: ["Western Indonesian Time"],
  ACT: ["ASEAN Common Time", "Acre Time"],
  AWST: ["Australian Western Standard Time"],
  BDT: ["Brunei Time", "Bangladesh Daylight Time"],
  CHOT: ["Choibalsan"],
  CIT: ["Central Indonesia Time"],
  CT: ["China time"],
  HKT: ["Hong Kong Time"],
  IRKT: ["Irkutsk Time"],
  MYT: ["Malaysia Time"],
  SGT: ["Singapore Time"],
  SST: ["Singapore Standard Time", "Samoa Standard Time"],
  ULAT: ["Ulaanbaatar Time"],
  WST: ["Western Standard Time"],
  CWST: ["Central Western Standard Time (Australia)"],
  AWDT: ["Australian Western Daylight Time"],
  EIT: ["Eastern Indonesian Time"],
  JST: ["Japan Standard Time"],
  KST: ["Korea Standard Time"],
  TLT: ["Timor Leste Time"],
  YAKT: ["Yakutsk Time"],
  ACST: ["Australian Central Standard Time"],
  AEST: ["Australian Eastern Standard Time"],
  ChST: ["Chamorro Standard Time"],
  CHUT: ["Chuuk Time"],
  DDUT: ["Dumont d'Urville Time"],
  PGT: ["Papua New Guinea Time"],
  VLAT: ["Vladivostok Time"],
  ACDT: ["Australian Central Daylight Savings Time"],
  LHST: ["Lord Howe Standard Time", "Lord Howe Summer Time"],
  AEDT: ["Australian Eastern Daylight Savings Time"],
  KOST: ["Kosrae Time"],
  MIST: ["Macquarie Island Station Time"],
  NCT: ["New Caledonia Time"],
  PONT: ["Pohnpei Standard Time"],
  SAKT: ["Sakhalin Island time"],
  SBT: ["Solomon Islands Time"],
  SRET: ["Srednekolymsk Time"],
  VUT: ["Vanuatu Time"],
  NFT: ["Norfolk Time"],
  FJT: ["Fiji Time"],
  GILT: ["Gilbert Island Time"],
  MAGT: ["Magadan Time"],
  MHT: ["Marshall Islands"],
  NZST: ["New Zealand Standard Time"],
  PETT: ["Kamchatka Time"],
  TVT: ["Tuvalu Time"],
  WAKT: ["Wake Island Time"],
  CHAST: ["Chatham Standard Time"],
  NZDT: ["New Zealand Daylight Time"],
  PHOT: ["Phoenix Island Time"],
  TKT: ["Tokelau Time"],
  TOT: ["Tonga Time"],
  CHADT: ["Chatham Daylight Time"],
  LINT: ["Line Islands Time"],
  AZOST: ["Azores Standard Time"],
  CVT: ["Cape Verde Time"],
  EGT: ["Eastern Greenland Time"],
  BRST: ["Brasilia Summer Time"],
  FNT: ["Fernando de Noronha Time"],
  GST: ["South Georgia and the South Sandwich Islands", "Gulf Standard Time"],
  PMDT: ["Saint Pierre and Miquelon Daylight time"],
  UYST: ["Uruguay Summer Time"],
  NDT: ["Newfoundland Daylight Time"],
  ADT: ["Atlantic Daylight Time"],
  AMST: ["Amazon Summer Time (Brazil)"],
  ART: ["Argentina Time"],
  BRT: ["Brasilia Time"],
  CLST: ["Chile Summer Time"],
  FKST: ["Falkland Islands Standard Time", "Falkland Islands Summer Time"],
  GFT: ["French Guiana Time"],
  PMST: ["Saint Pierre and Miquelon Standard Time"],
  PYST: ["Paraguay Summer Time (South America)"],
  ROTT: ["Rothera Research Station Time"],
  SRT: ["Suriname Time"],
  UYT: ["Uruguay Standard Time"],
  NST: ["Newfoundland Standard Time"],
  NT: ["Newfoundland Time"],
  AMT: ["Amazon Time (Brazil)", "Armenia Time"],
  AST: ["Atlantic Standard Time", "Arabia Standard Time"],
  BOT: ["Bolivia Time"],
  CLT: ["Chile Standard Time"],
  COST: ["Colombia Summer Time"],
  ECT: ["Eastern Caribbean Time", "Ecuador Time"],
  EDT: ["Eastern Daylight Time (North America)"],
  FKT: ["Falkland Islands Time"],
  GYT: ["Guyana Time"],
  PYT: ["Paraguay Time (South America)"],
  VET: ["Venezuelan Standard Time"],
  CDT: ["Central Daylight Time (North America)", "Cuba Daylight Time"],
  COT: ["Colombia Time"],
  EASST: ["Easter Island Standard Summer Time"],
  EST: ["Eastern Standard Time (North America)", "Australian Eastern Standard Time"],
  PET: ["Peru Time"],
  CST: ["Central Standard Time (North America)", "Cuba Standard Time", "China Standard Time", "Australia Central Standard Time", "Australia Central Summer Time"],
  EAST: ["Easter Island Standard Time"],
  GALT: ["Galapagos Time"],
  MDT: ["Mountain Daylight Time (North America)"],
  MST: ["Mountain Standard Time (North America)", "Malaysia Standard Time"],
  PDT: ["Pacific Daylight Time (North America)"],
  AKDT: ["Alaska Daylight Time"],
  CIST: ["Clipperton Island Standard Time"],
  PST: ["Pacific Standard Time (North America)", "Philippine Standard Time"],
  AKST: ["Alaska Standard Time"],
  GAMT: ["Gambier Islands"],
  GIT: ["Gambier Island Time"],
  HADT: ["Hawaii-Aleutian Daylight Time"],
  MART: ["Marquesas Islands Time"],
  MIT: ["Marquesas Islands Time"],
  CKT: ["Cook Island Time"],
  HAST: ["Hawaii-Aleutian Standard Time"],
  HST: ["Hawaii Standard Time"],
  TAHT: ["Tahiti Time"],
  NUT: ["Niue Time"],
  BIT: ["Baker Island Time"]
}.freeze

CODES = {
  "Greenwich Mean Time": "Etc/GMT",
  "International Business Standard Time": "UTC",
  "Western European Time" => "Europe/Lisbon",
  "Zulu Time (Coordinated Universal Time)" => "UTC",
  "Eastern Greenland Summer Time" => "America/Godthab",
  "British Summer Time" => "Europe/London",
  "Bangladesh Standard Time" => "Asia/Dhaka",
  "Bougainville Standard Time" => "Pacific/Bougainville",
  "Central European Time" => "Europe/Paris",
  "AIX specific equivalent of Central European Time" => "Europe/Paris",
  "Irish Standard Time" => "Europe/Dublin",
  "Indian Standard Time" => "Asia/Kolkata",
  "Israel Standard Time" => "Asia/Jerusalem",
  "Middle European Time Same zone as CET" => "Europe/Paris",
  "West Africa Time" => "Africa/Lagos",
  "Western European Daylight Time" => "Europe/Lisbon",
  "Western European Summer Time" => "Europe/Lisbon",
  "Central Africa Time" => "Africa/Harare",
  "Central European Daylight Time" => "Europe/Paris",
  "Central European Summer Time" => "Europe/Paris",
  "Eastern European Time" => "Europe/Athens",
  "Heure Avancée d'Europe Centrale" => "Europe/Paris",
  "Middle European Summer Time Same zone as CEST" => "Europe/Paris",
  "South African Standard Time" => "Africa/Johannesburg",
  "Kaliningrad Time" => "Europe/Kaliningrad",
  "West Africa Summer Time" => "Africa/Abidjan",
  "East Africa Time" => "Africa/Nairobi",
  "Eastern European Daylight Time" => "Europe/Tallinn",
  "Eastern European Summer Time" => "Europe/Tallinn",
  "Further-eastern European Time" => "Europe/Minsk",
  "Israel Daylight Time" => "Asia/Jerusalem",
  "Indian Ocean Time" => "Indian/Antananarivo",
  "Moscow Time" => "Europe/Moscow",
  "Showa Station Time" => "Antarctica/Syowa",
  "Iran Standard Time" => "Asia/Tehran",
  "Azerbaijan Time" => "Asia/Baku",
  "Georgia Standard Time" => "Asia/Tbilisi",
  "Mauritius Time" => "Indian/Mauritius",
  "Réunion Time" => "Indian/Reunion",
  "Samara Time" => "Asia/Samara",
  "Seychelles Time" => "Indian/Mahe",
  "Volgograd Time" => "Europe/Volgograd",
  "Afghanistan Time" => "Asia/Kabul",
  "Iran Daylight Time" => "Asia/Tehran",
  "Heard and McDonald Islands Time" => "Antarctica/Heard",
  "Mawson Station Time" => "Antarctica/Mawson",
  "Maldives Time" => "Indian/Maldives",
  "Oral Time" => "Asia/Oral",
  "Pakistan Standard Time" => "Asia/Karachi",
  "Indian/Kerguelen" => "Indian/Kerguelen",
  "Tajikistan Time" => "Asia/Dushanbe",
  "Turkmenistan Time" => "Asia/Ashgabat",
  "Uzbekistan Time" => "Asia/Tashkent",
  "Yekaterinburg Time" => "Asia/Yekaterinburg",
  "Sri Lanka Standard Time" => "Asia/Colombo",
  "Nepal Time" => "Asia/Kathmandu",
  "British Indian Ocean Time" => "Indian/Chagos",
  "Bhutan Time" => "Asia/Thimphu",
  "Kyrgyzstan time" => "Asia/Bishkek",
  "Omsk Time" => "Asia/Omsk",
  "Vostok Station Time" => "Antarctica/Vostok",
  "Cocos Islands Time" => "Indian/Cocos",
  "Myanmar Time" => "Asia/Yangon",
  "Myanmar Standard Time" => "Asia/Yangon",
  "Christmas Island Time" => "Australia/Christmas",
  "Davis Time" => "Antarctica/Davis",
  "Khovd Time" => "Asia/Hovd",
  "Indochina Time" => "Asia/Bangkok",
  "Krasnoyarsk Time" => "Asia/Krasnoyarsk",
  "Thailand Standard Time" => "Asia/Bangkok",
  "Western Indonesian Time" => "Asia/Jayapura",
  "ASEAN Common Time" => "America/Rio_Branco",
  "Acre Time" => "America/Rio_Branco",
  "Australian Western Standard Time" => "Australia/Perth",
  "Brunei Time" => "Asia/Brunei",
  "Bangladesh Daylight Time" => "Asia/Dhaka",
  "Choibalsan" => "Asia/Choibalsan",
  "Central Indonesia Time" => "Asia/Pontianak",
  "China time" => "Asia/Shanghai",
  "Hong Kong Time" => "Asia/Hong_Kong",
  "Irkutsk Time" => "Asia/Irkutsk",
  "Malaysia Time" => "Asia/Kuala_Lumpur",
  "Singapore Time" => "Asia/Singapore",
  "Singapore Standard Time" => "Asia/Singapore",
  "Samoa Standard Time" => "Pacific/Apia",
  "Ulaanbaatar Time" => "Asia/Ulaanbaatar",
  "Western Standard Time" => "Australia/Perth",
  "Central Western Standard Time (Australia)" => "Australia/Eucla",
  "Australian Western Daylight Time" => "Australia/Perth",
  "Eastern Indonesian Time" => "Asia/Jayapura",
  "Japan Standard Time" => "Asia/Tokyo",
  "Korea Standard Time" => "Asia/Seoul",
  "Timor Leste Time" => "Asia/Dili",
  "Yakutsk Time" => "Asia/Yakutsk",
  "Australian Central Standard Time" => "Australia/Adelaide",
  "Australian Eastern Standard Time" => "Australia/Sydney",
  "Chamorro Standard Time" => "Pacific/Guam",
  "Chuuk Time" => "Pacific/Chuuk",
  "Dumont d'Urville Time" => "Antarctica/DumontDUrville",
  "Papua New Guinea Time" => "Pacific/Port_Moresby",
  "Vladivostok Time" => "Asia/Vladivostok",
  "Australian Central Daylight Savings Time" => "Australia/Adelaide",
  "Lord Howe Standard Time" => "Australia/Lord_Howe",
  "Lord Howe Summer Time" => "Australia/Lord_Howe",
  "Australian Eastern Daylight Savings Time" => "Australia/Sydney",
  "Kosrae Time" => "Pacific/Kosrae",
  "Macquarie Island Station Time" => "Australia/Macquarie",
  "New Caledonia Time" => "Pacific/Noumea",
  "Pohnpei Standard Time" => "Pacific/Pohnpei",
  "Sakhalin Island time" => "Asia/Sakhalin",
  "Solomon Islands Time" => "Pacific/Guadalcanal",
  "Srednekolymsk Time" => "Asia/Kolyma",
  "Vanuatu Time" => "Pacific/Efate",
  "Norfolk Time" => "Pacific/Norfolk",
  "Fiji Time" => "Pacific/Fiji",
  "Gilbert Island Time" => "Pacific/Tarawa",
  "Magadan Time" => "Asia/Magadan",
  "Marshall Islands" => "Pacific/Majuro",
  "New Zealand Standard Time" => "Pacific/Auckland",
  "Kamchatka Time" => "Asia/Kamchatka",
  "Tuvalu Time" => "Pacific/Tuvalu",
  "Wake Island Time" => "Pacific/Wake",
  "Chatham Standard Time" => "Pacific/Chatham",
  "New Zealand Daylight Time" => "Pacific/Auckland",
  "Phoenix Island Time" => "Pacific/Enderbury",
  "Tokelau Time" => "Pacific/Tokelau",
  "Tonga Time" => "Pacific/Tongatapu",
  "Chatham Daylight Time" => "Pacific/Chatham",
  "Line Islands Time" => "Pacific/Kiritimati",
  "Azores Standard Time" => "Atlantic/Azores",
  "Cape Verde Time" => "Atlantic/Cape_Verde",
  "Eastern Greenland Time" => "America/Godthab",
  "Brasilia Summer Time" => "America/Sao_Paulo",
  "Fernando de Noronha Time" => "America/Noronha",
  "South Georgia and the South Sandwich Islands" => "Atlantic/South_Georgia",
  "Gulf Standard Time" => "Asia/Dubai",
  "Saint Pierre and Miquelon Daylight Time" => "America/St_Pierre",
  "Uruguay Summer Time" => "America/Montevideo",
  "Newfoundland Daylight Time" => "America/St_Johns",
  "Atlantic Daylight Time" => "America/Halifax",
  "Amazon Summer Time" => "America/Belem",
  "Argentina Time" => "America/Argentina/Buenos_Aires",
  "Brasilia Time" => "America/Sao_Paulo",
  "Chile Continental Time" => "Chile/Continental",
  "Falkland Islands Standard Time" => "Atlantic/Stanley",
  "French Guiana Time" => "America/Cayenne",
  "Saint Pierre and Miquelon Standard Time" => "America/St_Pierre",
  "Paraguay Time" => "America/Asuncion",
  "Rothera Time" => "Antarctica/Rothera",
  "Suriname Time" => "America/Paramaribo",
  "Uruguay Time" => "America/Montevideo",
  "Newfoundland Standard Time" => "America/St_Johns",
  "Atlantic Standard Time" => "America/St_Johns",
  "Armenian Time" => "Asia/Yerevan",
  "Arabian Standard Time" => "Asia/Riyadh",
  "Bolivia Time" => "America/La_Paz",
  "Chile Standard Time" => "Chile/Continental",
  "Colombia Time" => "America/Bogota",
  "Ecuador Time" => "America/Guayaquil",
  "Eastern Daylight Time" => "America/New_York",
  "Falkland Islands Time" => "Atlantic/Stanley",
  "Guyana Time" => "America/Guyana",
  "Paraguayan Time" => "America/Asuncion",
  "Venezuelan Standard Time" => "America/Caracas",
  "Central Daylight Time (North America)" => "America/Chicago",
  "Cuba Daylight Time" => "America/Havana",
  "Easter Island Standard Summer Time" => "Pacific/Easter",
  "Eastern Standard Time (North America)" => "America/New_York",
  "Peru Time" => "America/Lima",
  "Central Standard Time (North America)" => "America/Chicago",
  "Cuba Standard Time" => "America/Havana",
  "China Standard Time" => "Asia/Shanghai",
  "Australia Central Standard Time" => "Australia/Adelaide",
  "Australia Central Summer Time" => "Australia/Adelaide",
  "Easter Island Standard Time" => "Pacific/Easter",
  "Galapagos Time" => "Pacific/Galapagos",
  "Mountain Daylight Time (North America)" => "America/Denver",
  "Mountain Standard Time (North America)" => "America/Denver",
  "Malaysia Standard Time" => "Asia/Kuala_Lumpur",
  "Pacific Daylight Time (North America)" => "America/Los_Angeles",
  "Alaska Daylight Time" => "America/Anchorage",
  "Clipperton Island Standard Time" => "Pacific/Clipperton",
  "Pacific Standard Time (North America)" => "America/Los_Angeles",
  "Philippine Standard Time" => "Asia/Manila",
  "Alaska Standard Time" => "America/Anchorage",
  "Gambier Islands" => "Pacific/Gambier",
  "Gambier Island Time" => "Pacific/Gambier",
  "Hawaii-Aleutian Daylight Time" => "America/Adak",
  "Marquesas Islands Time" => "Pacific/Marquesas",
  "Cook Island Time" => "Pacific/Rarotonga",
  "Hawaii-Aleutian Standard Time" => "America/Adak",
  "Hawaii Standard Time" => "Pacific/Honolulu",
  "Tahiti Time" => "Pacific/Tahiti",
  "Niue Time" => "Pacific/Niue",
  "Baker Island Time" => "Pacific/Baker"
}.freeze
